#!/bin/bash

# Ly module - TUI display manager for Hyprland
# Installs and configures ly display manager with Hyprland session support

# Module metadata
MODULE_NAME="ly"
MODULE_DESCRIPTION="Ly TUI display manager for Hyprland"
MODULE_REQUIRES=("base" "hyprland")

# Required packages
OFFICIAL_PACKAGES=()
AUR_PACKAGES=("ly")

# Services to enable
SERVICES=("ly.service")
USER_SERVICES=()

# Helper function: Detect conflicting display managers
detect_display_manager_conflicts() {
    log_info "Checking for conflicting display managers..."

    # List of common display managers to check
    local display_managers=(
        "gdm.service"
        "lightdm.service"
        "sddm.service"
        "lxdm.service"
        "xdm.service"
        "entrance.service"
        "slim.service"
        "nodm.service"
    )

    local conflicts=()

    # Check if any DM service is enabled
    for dm in "${display_managers[@]}"; do
        if is_service_enabled "$dm"; then
            conflicts+=("$dm")
        fi
    done

    # If conflicts found, handle them
    if [[ ${#conflicts[@]} -gt 0 ]]; then
        log_warn "Found enabled display manager(s): ${conflicts[*]}"

        if [[ "${DRY_RUN:-false}" == "true" ]]; then
            log_info "[DRY RUN] Would disable: ${conflicts[*]}"
            return 0
        fi

        # Ask user for confirmation
        log_info "The following display managers must be disabled:"
        for dm in "${conflicts[@]}"; do
            log_info "  - $dm"
        done

        if ! confirm_prompt "Disable conflicting display managers?" "y"; then
            log_error "Cannot proceed without disabling conflicting display managers"
            return 1
        fi

        # Disable each conflicting DM
        for dm in "${conflicts[@]}"; do
            log_info "Disabling $dm..."
            if sudo systemctl disable "$dm"; then
                log_success "Disabled $dm"
            else
                log_error "Failed to disable $dm"
                return 1
            fi
        done
    else
        log_success "No conflicting display managers found"
    fi

    return 0
}

# Helper function: Generate ly configuration
generate_ly_config() {
    local config_file="/etc/ly/config.ini"

    log_info "Generating Ly configuration at $config_file..."

    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "[DRY RUN] Would generate $config_file"
        return 0
    fi

    # Backup existing config if present
    if [[ -f "$config_file" ]]; then
        backup_file "$config_file" || log_warn "Could not backup existing config"
    fi

    # Read config values from config.toml
    local enable_autologin=$(get_config "ly.enable_autologin" "false")
    local autologin_user=$(get_config "ly.autologin_user" "")
    local tty=$(get_config "ly.tty" "2")
    local animate=$(get_config "ly.animate" "false")
    local hide_borders=$(get_config "ly.hide_borders" "false")

    # Validate auto-login settings
    if [[ "$enable_autologin" == "true" && -z "$autologin_user" ]]; then
        log_error "Auto-login enabled but no username specified in config.toml"
        log_error "Set ly.autologin_user in config/config.toml"
        return 1
    fi

    # Generate config.ini
    cat > /tmp/ly-config.ini << EOF
# Ly Display Manager Configuration
# Generated by arch-setup framework
# Edit /etc/ly/config.ini or config/config.toml to modify

# TTY where ly will run
tty = $tty

# Visual effects
animate = $animate
hide_borders = $hide_borders

# Session configuration
# Ly will automatically detect sessions from /usr/share/wayland-sessions/ and /usr/share/xsessions/

# Auto-login configuration
EOF

    if [[ "$enable_autologin" == "true" ]]; then
        cat >> /tmp/ly-config.ini << EOF
# WARNING: Auto-login reduces security
save = true
save_file = /etc/ly/save
EOF
        # Create save file for auto-login
        echo "$autologin_user" | sudo tee /etc/ly/save > /dev/null
        sudo chmod 600 /etc/ly/save
        log_info "Auto-login configured for user: $autologin_user"
    else
        cat >> /tmp/ly-config.ini << EOF
# Auto-login disabled for security
save = false
EOF
    fi

    # Move generated config to final location
    if sudo mv /tmp/ly-config.ini "$config_file"; then
        sudo chmod 644 "$config_file"
        log_success "Ly configuration created at $config_file"
        return 0
    else
        log_error "Failed to create Ly configuration"
        return 1
    fi
}

# Helper function: Disable getty service on ly's TTY
disable_getty_service() {
    local tty_number="$1"
    local getty_service="getty@tty${tty_number}.service"

    log_info "Disabling $getty_service to prevent conflicts with Ly..."

    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "[DRY RUN] Would disable $getty_service"
        return 0
    fi

    if is_service_enabled "$getty_service"; then
        if sudo systemctl disable "$getty_service"; then
            log_success "Disabled $getty_service"
        else
            log_warn "Failed to disable $getty_service (may not be critical)"
        fi
    else
        log_info "$getty_service is already disabled"
    fi

    return 0
}

# Module installation hook
module_install() {
    log_info "Installing Ly display manager..."

    # Detect and handle conflicting display managers
    detect_display_manager_conflicts || return 1

    # Verify Hyprland is installed
    if ! is_installed "hyprland"; then
        log_error "Hyprland is not installed. Ly module requires Hyprland."
        log_error "Enable the hyprland module in config.toml first."
        return 1
    fi

    # Warn if Hyprland session file missing (may be created later)
    if [[ ! -f "/usr/share/wayland-sessions/hyprland.desktop" ]]; then
        log_warn "Hyprland session file not found at /usr/share/wayland-sessions/hyprland.desktop"
        log_warn "This may prevent Ly from launching Hyprland sessions"
    fi

    return 0
}

# Module configuration hook
module_configure() {
    log_info "Configuring Ly display manager..."

    # Ensure config directory exists
    sudo mkdir -p /etc/ly || {
        log_error "Failed to create /etc/ly directory"
        return 1
    }

    # Generate config from config.toml settings
    generate_ly_config || return 1

    # Disable getty on the TTY ly will use
    local ly_tty=$(get_config "ly.tty" "2")
    disable_getty_service "$ly_tty"

    return 0
}

# Post-install hook
module_post_install() {
    log_success "Ly display manager installed successfully"
    log_info ""
    log_info "Ly Configuration:"
    log_info "  - Config file: /etc/ly/config.ini"
    log_info "  - Service: ly.service (will start on boot)"
    log_info "  - TTY: $(get_config 'ly.tty' '2')"
    log_info "  - Default session: Hyprland"

    local autologin=$(get_config "ly.enable_autologin" "false")
    if [[ "$autologin" == "true" ]]; then
        local username=$(get_config "ly.autologin_user" "")
        log_info "  - Auto-login: ENABLED for user '$username'"
        log_warn "    WARNING: Auto-login reduces system security"
    else
        log_info "  - Auto-login: DISABLED (manual login required)"
    fi

    log_info ""
    log_info "Next steps:"
    log_info "  1. Reboot your system: sudo reboot"
    log_info "  2. Ly will start automatically on TTY $(get_config 'ly.tty' '2')"
    log_info "  3. Select Hyprland from the session menu and login"

    return 0
}
